import { ThemeDef } from "../types.js";

export const cyberpunk: ThemeDef = {
  name: "cyberpunk",
  display: "Tron x Gotham",
  description: "Cyan neon grid meets dark Gotham noir",
  colors: {
    accentPrimary: "#00D4FF",
    accentHover: "#00A8CC",
    accentSecondary: "#FF2E63",
    bgPrimary: "#06080C",
    bgSecondary: "#0B0F18",
    bgTertiary: "#111827",
    textPrimary: "#E0E6F0",
    textSecondary: "#8892A8",
    textTertiary: "#4A5568",
    border: "#1A2236",
    borderActive: "#00D4FF",
    success: "#00FF88",
    warning: "#FFB800",
    error: "#FF2E63",
    info: "#00D4FF",
    cyan: "#00D4FF",
    lime: "#39FF14",
    amber: "#FFB800",
    magenta: "#FF2E63",
    purple: "#8B5CF6",
  },
  effects: {
    scanlines: true,
    glow: true,
    pulse: true,
    grid: true,
    chamferButtons: true,
    accentBar: true,
    glowIntensity: 0.6,
    scanlineOpacity: 0.03,
  },
};

export const light: ThemeDef = {
  name: "light",
  display: "Light",
  description: "Clean light theme",
  colors: {
    accentPrimary: "#0066FF",
    accentHover: "#0052CC",
    accentSecondary: "#7C3AED",
    bgPrimary: "#FFFFFF",
    bgSecondary: "#F8F9FA",
    bgTertiary: "#E9ECEF",
    textPrimary: "#212529",
    textSecondary: "#495057",
    textTertiary: "#868E96",
    border: "#DEE2E6",
    borderActive: "#0066FF",
    success: "#2ECC71",
    warning: "#F39C12",
    error: "#E74C3C",
    info: "#3498DB",
    cyan: "#00BCD4",
    lime: "#8BC34A",
    amber: "#FFC107",
    magenta: "#E91E63",
    purple: "#9C27B0",
  },
};

export const dark: ThemeDef = {
  name: "dark",
  display: "Dark",
  description: "Classic dark theme",
  colors: {
    accentPrimary: "#58A6FF",
    accentHover: "#4090E0",
    accentSecondary: "#D2A8FF",
    bgPrimary: "#0D1117",
    bgSecondary: "#161B22",
    bgTertiary: "#21262D",
    textPrimary: "#E6EDF3",
    textSecondary: "#B1BAC4",
    textTertiary: "#7D8590",
    border: "#30363D",
    borderActive: "#58A6FF",
    success: "#3FB950",
    warning: "#D29922",
    error: "#F85149",
    info: "#58A6FF",
    cyan: "#39D2C0",
    lime: "#7EE787",
    amber: "#E3B341",
    magenta: "#FF7B72",
    purple: "#D2A8FF",
  },
};

export const matrix: ThemeDef = {
  name: "matrix",
  display: "Matrix",
  description: "Green terminal aesthetic",
  colors: {
    accentPrimary: "#00FF41",
    accentHover: "#00CC33",
    accentSecondary: "#008F11",
    bgPrimary: "#0D0208",
    bgSecondary: "#0A0A0A",
    bgTertiary: "#141414",
    textPrimary: "#00FF41",
    textSecondary: "#00CC33",
    textTertiary: "#008F11",
    border: "#003B00",
    borderActive: "#00FF41",
    success: "#00FF41",
    warning: "#ADFF2F",
    error: "#FF0000",
    info: "#00FF41",
    cyan: "#00FF41",
    lime: "#32CD32",
    amber: "#7CFC00",
    magenta: "#00FA9A",
    purple: "#00FF7F",
  },
  effects: { scanlines: true, glow: true, grid: true, glowIntensity: 0.3, scanlineOpacity: 0.05 },
};

export const tron: ThemeDef = {
  name: "tron",
  display: "Tron",
  description: "Cyan grid aesthetic",
  colors: {
    accentPrimary: "#00DFFF",
    accentHover: "#00B8CF",
    accentSecondary: "#FF6600",
    bgPrimary: "#0A0A12",
    bgSecondary: "#0F0F1A",
    bgTertiary: "#161625",
    textPrimary: "#D4E4FF",
    textSecondary: "#8CACFF",
    textTertiary: "#5A7099",
    border: "#1A3050",
    borderActive: "#00DFFF",
    success: "#00FF88",
    warning: "#FFD700",
    error: "#FF4444",
    info: "#00DFFF",
    cyan: "#00DFFF",
    lime: "#00FF88",
    amber: "#FFD700",
    magenta: "#FF6600",
    purple: "#6644FF",
  },
  effects: { grid: true, glow: true, glowIntensity: 0.6 },
};

export const neon: ThemeDef = {
  name: "neon",
  display: "Neon",
  description: "Purple neon aesthetic",
  colors: {
    accentPrimary: "#BD34FE",
    accentHover: "#9B2DDB",
    accentSecondary: "#FF0080",
    bgPrimary: "#0B0014",
    bgSecondary: "#120020",
    bgTertiary: "#1A0030",
    textPrimary: "#E8D5FF",
    textSecondary: "#B88AE0",
    textTertiary: "#7A5A99",
    border: "#3D1A66",
    borderActive: "#BD34FE",
    success: "#00FF88",
    warning: "#FFD700",
    error: "#FF3366",
    info: "#BD34FE",
    cyan: "#00E5FF",
    lime: "#76FF03",
    amber: "#FFD740",
    magenta: "#FF0080",
    purple: "#BD34FE",
  },
  effects: { glow: true, pulse: true, glowIntensity: 0.7 },
};

export const terminal: ThemeDef = {
  name: "terminal",
  display: "Terminal",
  description: "Classic green terminal",
  colors: {
    accentPrimary: "#33FF00",
    accentHover: "#28CC00",
    accentSecondary: "#00AA00",
    bgPrimary: "#000000",
    bgSecondary: "#0A0A0A",
    bgTertiary: "#141414",
    textPrimary: "#33FF00",
    textSecondary: "#00CC00",
    textTertiary: "#008800",
    border: "#004400",
    borderActive: "#33FF00",
    success: "#33FF00",
    warning: "#FFFF00",
    error: "#FF0000",
    info: "#00CC00",
    cyan: "#00CCCC",
    lime: "#33FF00",
    amber: "#CCCC00",
    magenta: "#CC00CC",
    purple: "#9900CC",
  },
  effects: { scanlines: true, scanlineOpacity: 0.04 },
};

export const blood: ThemeDef = {
  name: "blood",
  display: "Blood",
  description: "Dark red aesthetic",
  colors: {
    accentPrimary: "#FF0040",
    accentHover: "#CC0033",
    accentSecondary: "#FF6600",
    bgPrimary: "#0A0004",
    bgSecondary: "#120008",
    bgTertiary: "#1A000C",
    textPrimary: "#FFD5DD",
    textSecondary: "#CC8899",
    textTertiary: "#885566",
    border: "#4A0020",
    borderActive: "#FF0040",
    success: "#44FF44",
    warning: "#FFAA00",
    error: "#FF0040",
    info: "#FF6688",
    cyan: "#00CCCC",
    lime: "#44FF44",
    amber: "#FFAA00",
    magenta: "#FF0088",
    purple: "#AA00FF",
  },
  effects: { glow: true, glowIntensity: 0.4 },
};

export const sunset: ThemeDef = {
  name: "sunset",
  display: "Sunset",
  description: "Warm sunset aesthetic",
  colors: {
    accentPrimary: "#FF6B35",
    accentHover: "#E05A28",
    accentSecondary: "#F7931E",
    bgPrimary: "#1A0A00",
    bgSecondary: "#241000",
    bgTertiary: "#2E1800",
    textPrimary: "#FFE4CC",
    textSecondary: "#CC9977",
    textTertiary: "#996644",
    border: "#5A3010",
    borderActive: "#FF6B35",
    success: "#7BC950",
    warning: "#F7931E",
    error: "#FF3B30",
    info: "#FF6B35",
    cyan: "#4ECDC4",
    lime: "#7BC950",
    amber: "#F7931E",
    magenta: "#FF3366",
    purple: "#9B59B6",
  },
};

export const ocean: ThemeDef = {
  name: "ocean",
  display: "Ocean",
  description: "Deep blue ocean aesthetic",
  colors: {
    accentPrimary: "#0077BE",
    accentHover: "#005F99",
    accentSecondary: "#00B4D8",
    bgPrimary: "#001219",
    bgSecondary: "#001D2B",
    bgTertiary: "#002838",
    textPrimary: "#CAE9FF",
    textSecondary: "#7EB8DA",
    textTertiary: "#4A8AAF",
    border: "#003D5B",
    borderActive: "#0077BE",
    success: "#00E676",
    warning: "#FFB74D",
    error: "#FF5252",
    info: "#00B4D8",
    cyan: "#00B4D8",
    lime: "#00E676",
    amber: "#FFB74D",
    magenta: "#CE93D8",
    purple: "#7E57C2",
  },
};

export const midnight: ThemeDef = {
  name: "midnight",
  display: "Midnight",
  description: "Dark blue midnight aesthetic",
  colors: {
    accentPrimary: "#667EEA",
    accentHover: "#5468C8",
    accentSecondary: "#764BA2",
    bgPrimary: "#0B0E1A",
    bgSecondary: "#101428",
    bgTertiary: "#161A35",
    textPrimary: "#D0D5F0",
    textSecondary: "#8E95C0",
    textTertiary: "#5A6090",
    border: "#252B50",
    borderActive: "#667EEA",
    success: "#48BB78",
    warning: "#ECC94B",
    error: "#FC8181",
    info: "#63B3ED",
    cyan: "#63B3ED",
    lime: "#48BB78",
    amber: "#ECC94B",
    magenta: "#ED64A6",
    purple: "#9F7AEA",
  },
};

export const paper: ThemeDef = {
  name: "paper",
  display: "Paper",
  description: "Sepia paper aesthetic",
  colors: {
    accentPrimary: "#8B4513",
    accentHover: "#703610",
    accentSecondary: "#A0522D",
    bgPrimary: "#F5F0E8",
    bgSecondary: "#EDE6D8",
    bgTertiary: "#E0D5C3",
    textPrimary: "#3E2723",
    textSecondary: "#5D4037",
    textTertiary: "#8D6E63",
    border: "#BCAAA4",
    borderActive: "#8B4513",
    success: "#558B2F",
    warning: "#F57F17",
    error: "#C62828",
    info: "#1565C0",
    cyan: "#00838F",
    lime: "#558B2F",
    amber: "#F57F17",
    magenta: "#AD1457",
    purple: "#6A1B9A",
  },
};

export const forest: ThemeDef = {
  name: "forest",
  display: "Forest",
  description: "Green forest aesthetic",
  colors: {
    accentPrimary: "#4CAF50",
    accentHover: "#3D9140",
    accentSecondary: "#8BC34A",
    bgPrimary: "#0A1A0A",
    bgSecondary: "#0F250F",
    bgTertiary: "#143014",
    textPrimary: "#C8E6C9",
    textSecondary: "#81C784",
    textTertiary: "#4CAF50",
    border: "#1B4D1B",
    borderActive: "#4CAF50",
    success: "#69F0AE",
    warning: "#FFD54F",
    error: "#EF5350",
    info: "#29B6F6",
    cyan: "#26A69A",
    lime: "#8BC34A",
    amber: "#FFD54F",
    magenta: "#EC407A",
    purple: "#AB47BC",
  },
};

export const mono: ThemeDef = {
  name: "mono",
  display: "Mono",
  description: "Grayscale monochrome aesthetic",
  colors: {
    accentPrimary: "#FFFFFF",
    accentHover: "#CCCCCC",
    accentSecondary: "#999999",
    bgPrimary: "#000000",
    bgSecondary: "#0A0A0A",
    bgTertiary: "#141414",
    textPrimary: "#FFFFFF",
    textSecondary: "#AAAAAA",
    textTertiary: "#666666",
    border: "#333333",
    borderActive: "#FFFFFF",
    success: "#CCCCCC",
    warning: "#999999",
    error: "#FFFFFF",
    info: "#BBBBBB",
    cyan: "#CCCCCC",
    lime: "#DDDDDD",
    amber: "#AAAAAA",
    magenta: "#999999",
    purple: "#BBBBBB",
  },
};

export const opencode: ThemeDef = {
  name: "opencode",
  display: "OpenCode",
  description: "Restrained muted dark palette with a calm teal accent",
  colors: {
    accentPrimary: "#5FB3A1",
    accentHover: "#4E9384",
    accentSecondary: "#7FB685",
    bgPrimary: "#0E0E10",
    bgSecondary: "#141416",
    bgTertiary: "#1C1C20",
    textPrimary: "#D7D7D2",
    textSecondary: "#8A8A86",
    textTertiary: "#56565A",
    border: "#26262B",
    borderActive: "#5FB3A1",
    success: "#6FB58A",
    warning: "#C9A26A",
    error: "#C76B6B",
    info: "#5FB3A1",
    cyan: "#5FB3A1",
    lime: "#7FB685",
    amber: "#C9A26A",
    magenta: "#B08AA8",
    purple: "#9785B5",
  },
};

// ─── new high-vibe themes: cyberpunk × tron, tuned for color separation ──────
// Each palette is built so the renderer's color ROLES read at a glance:
//   cyan    = code + inline code + the prompt ❯
//   lime    = diff additions + success + ready dot
//   error   = diff deletions + errors + the no-provider warning
//   amber   = slash-command hints + working indicator + scroll hint
//   accent  = headings + active borders + the user bubble
//   magenta = the secondary accent (tool-call rails, counters)

/** Vaporwave — pink/cyan on deep indigo, A E S T H E T I C. */
export const vaporwave: ThemeDef = {
  name: "vaporwave",
  display: "Vaporwave",
  description: "Pink-cyan dream on deep indigo (▓▒░ aesthetic)",
  colors: {
    accentPrimary: "#FF71CE",
    accentHover: "#FF49B8",
    accentSecondary: "#01CDFE",
    bgPrimary: "#1A0033",
    bgSecondary: "#2D0050",
    bgTertiary: "#3D0066",
    textPrimary: "#F0F0FF",
    textSecondary: "#B8A0D8",
    textTertiary: "#7A5C99",
    border: "#4D2080",
    borderActive: "#FF71CE",
    success: "#05FFA1",
    warning: "#FFB800",
    error: "#FF3864",
    info: "#01CDFE",
    cyan: "#01CDFE",
    lime: "#05FFA1",
    amber: "#FFB800",
    magenta: "#FF71CE",
    purple: "#B967FF",
  },
  effects: { glow: true, pulse: true, glowIntensity: 0.5 },
};

/** Synthwave — magenta sun + electric blue grid, the Drive vibe. */
export const synthwave: ThemeDef = {
  name: "synthwave",
  display: "Synthwave",
  description: "Magenta sun over an electric-blue grid",
  colors: {
    accentPrimary: "#FF4081",
    accentHover: "#E63A75",
    accentSecondary: "#00E5FF",
    bgPrimary: "#0D0221",
    bgSecondary: "#1A0933",
    bgTertiary: "#260F44",
    textPrimary: "#FEE7FF",
    textSecondary: "#C4A0E0",
    textTertiary: "#8A6BB0",
    border: "#3D1A66",
    borderActive: "#FF4081",
    success: "#00FF9F",
    warning: "#FFD000",
    error: "#FF2052",
    info: "#00E5FF",
    cyan: "#00E5FF",
    lime: "#00FF9F",
    amber: "#FFD000",
    magenta: "#FF4081",
    purple: "#9D00FF",
  },
  effects: { grid: true, glow: true, scanlines: true, glowIntensity: 0.65, scanlineOpacity: 0.04 },
};

/** Outrun — sunset gradient on black, hot orange + teal, pure 1986. */
export const outrun: ThemeDef = {
  name: "outrun",
  display: "Outrun",
  description: "Sunset strip: hot orange + teal on black",
  colors: {
    accentPrimary: "#FF6B35",
    accentHover: "#E55A2B",
    accentSecondary: "#00F0FF",
    bgPrimary: "#0A0014",
    bgSecondary: "#14001F",
    bgTertiary: "#1F002D",
    textPrimary: "#FFF5E6",
    textSecondary: "#D8A880",
    textTertiary: "#996655",
    border: "#4D1A00",
    borderActive: "#FF6B35",
    success: "#00FF88",
    warning: "#FFD700",
    error: "#FF2E63",
    info: "#00F0FF",
    cyan: "#00F0FF",
    lime: "#00FF88",
    amber: "#FFAA00",
    magenta: "#FF2E63",
    purple: "#C400FF",
  },
  effects: { grid: true, glow: true, glowIntensity: 0.6 },
};

/** Glitch — acid green + hot pink, high-contrast, terminal-punk. */
export const glitch: ThemeDef = {
  name: "glitch",
  display: "Glitch",
  description: "Acid green + hot pink, high-contrast terminal punk",
  colors: {
    accentPrimary: "#00FF41",
    accentHover: "#00CC33",
    accentSecondary: "#FF0099",
    bgPrimary: "#000000",
    bgSecondary: "#0A0A0A",
    bgTertiary: "#141414",
    textPrimary: "#E0FFE0",
    textSecondary: "#88CC88",
    textTertiary: "#446644",
    border: "#1A331A",
    borderActive: "#00FF41",
    success: "#00FF41",
    warning: "#FFEE00",
    error: "#FF0099",
    info: "#00DDFF",
    cyan: "#00DDFF",
    lime: "#00FF41",
    amber: "#FFEE00",
    magenta: "#FF0099",
    purple: "#AA00FF",
  },
  effects: { scanlines: true, glow: true, glowIntensity: 0.4, scanlineOpacity: 0.05 },
};

/** Hologram — iridescent cyan-violet, clean and futuristic. */
export const hologram: ThemeDef = {
  name: "hologram",
  display: "Hologram",
  description: "Iridescent cyan-violet, clean and futuristic",
  colors: {
    accentPrimary: "#00FFF5",
    accentHover: "#00D9D0",
    accentSecondary: "#BF00FF",
    bgPrimary: "#050514",
    bgSecondary: "#0A0A1F",
    bgTertiary: "#101030",
    textPrimary: "#E6FFFF",
    textSecondary: "#90C0D8",
    textTertiary: "#507088",
    border: "#1A3045",
    borderActive: "#00FFF5",
    success: "#00FFAA",
    warning: "#FFE000",
    error: "#FF3070",
    info: "#00FFF5",
    cyan: "#00FFF5",
    lime: "#00FFAA",
    amber: "#FFE000",
    magenta: "#FF30D0",
    purple: "#BF00FF",
  },
  effects: { glow: true, grid: true, pulse: true, glowIntensity: 0.55 },
};

export const ALL_THEMES: ThemeDef[] = [
  cyberpunk,
  light,
  dark,
  matrix,
  tron,
  neon,
  terminal,
  blood,
  sunset,
  ocean,
  midnight,
  paper,
  forest,
  mono,
  opencode,
  // New high-vibe themes — cyberpunk-meets-tron with strong color separation.
  vaporwave,
  synthwave,
  outrun,
  glitch,
  hologram,
];
